### ISSUE TITLE
during linting , the values.schema.json does not get enforced

### ISSUE THREAD

**Issue by RonaldCrb** [helm/chart-testing#193]
## Is this a request for help?
Sort of...

## Is this a BUG REPORT or FEATURE REQUEST?
More like a Feature question

## Expected behaviour
when linting, the values should be validated against the values.schema.json file in a similar fashion than with the traditional helm cli. 

```shell
[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
internship:
- envVars: ENV_VAR1 is required
- envVars: ENV_VAR2 is required
- envVars: ENV_VAR3 is required
- envVars: ENV_VAR4 is required
- envVars: ENV_VAR5 is required
```

## Actual behaviour 
the linting passes even when some of the values are missing. as if the values.schema.json was not present. 

## the context of execution
GitlabCI runner using the following docker image:

quay.io/helmpack/chart-testing:latest 

this is the gitlab-ci.yml file

```yaml
lint:
  stage: test
  image: quay.io/helmpack/chart-testing
  tags: ['k8s']
  script:
    - ct lint --config config.yaml
  except:
    - master
```

my config file looks like this:

``` yaml
# The name of the Git remote
remote: origin

# Chart directories separated by a space
chart-dirs:
  - charts/current
  # - charts/v3

# Charts that should be skipped
excluded_charts:
  - charts/deprecated
```

the actual output is this
```shell
No requirements found in charts/current/internship/charts.
130 Linting chart 'internship => (version: "2.0.0", path: "charts/current/internship")'
131 Checking chart 'internship => (version: "2.0.0", path: "charts/current/internship")' for a version bump...
132 Old chart version: 1.0.0
133 New chart version: 2.0.0
134 Chart version ok.
135 Validating /builds/<MASKED>/devops/helm/charts/current/internship/Chart.yaml...
136 Validation success! 👍
137 Validating maintainers...
138 ==> Linting charts/current/internship
139 [INFO] Chart.yaml: icon is recommended
140 1 chart(s) linted, no failures
```
