### ISSUE TITLE
ExcludedCharts does not work with multi-level ChartDirs

### ISSUE THREAD

**Issue by stawii** [helm/chart-testing#311]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

N/A

**What happened**:

ExcludedCharts does not work when ChartDirs contains path with more than one level: ie. `charts/apps` or `charts/my/path/is/longer/than/yours`.

**What you expected to happen**:

Chart is excluded correctly.

**How to reproduce it** (as minimally and precisely as possible):

```yaml
chart-dirs:
  - charts/apps

excluded-charts: # neither of those works
  - charts/apps/chart-name
  - chart-name
```

**Anything else we need to know**:

I guess it is this line https://github.com/helm/chart-testing/blob/2407e7df462ea3bc85cefd9b5870526bc7806a9f/pkg/chart/chart.go#L721 - the `pathElements` is [charts, apps, chart-name], so chart name is 2 not 1 in this example. This will be different if path has more levels.
