### ISSUE TITLE
Test and warn duplicate keys in yaml

### ISSUE THREAD

**Issue by paologallinaharbur** [helm/chart-testing#344]
**Feature request**
I saw in the Helm repository this issue marked as `willnotfix` https://github.com/helm/helm/issues/5524 since it was out of scope with `helm lint` and would have required the implementation of a custom yaml parser.

I tested and neigher `ct` is  capable of detecting that the following yaml is not the best:
```yaml
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
        volumeMounts:
        - name: tls-key-cert-pair
          mountPath: /etc/tls-key-cert-pair
```

Is it feasible to add this kind of validation?
