### ISSUE TITLE
Multiple custom values files not being validated

### ISSUE THREAD

**Issue by matthewmuscat** [helm/chart-testing#397]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Version of Helm and Kubernetes**:

**What happened**:
As suggested by the "What do you expect to happen" section below, `ct-lint` is not validating the values yaml configs. It is for some reason searching for the default `values.yaml` which does not exist (because I don't need it).

What I'm running:
```
ct lint --target-branch main --charts k8s/helm --debug --print-config
```

Error:

```
Validating /repo/k8s/helm/Chart.yaml...
Validation success! 👍
>>> yamllint --config-file /usr/local/etc/ct/lintconf.yaml k8s/helm/Chart.yaml
>>> yamllint --config-file /usr/local/etc/ct/lintconf.yaml k8s/helm/values.yaml
[Errno 2] No such file or directory: 'k8s/helm/values.yaml'
```

Folder Structure:

![image](https://user-images.githubusercontent.com/25076909/154891851-bca842b9-f0ef-4a3e-b2f9-d399e5798954.png)

GitHub Action workflow (specifies versions):

```
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --charts k8s/helm --debug --print-config
```

**What you expected to happen**:
> [Charts may have multiple custom values files matching the glob pattern '*-values.yaml' in a directory named 'ci' in the root of the chart's directory. The chart is linted for each of these files. If no custom values file is present, the chart is linted with defaults.](https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md#synopsis)

I would expect that each of the three dev/staging/prod value yaml's are validated. They have been nested within a `ci` folder, although it just seems like they aren't being detected?

**How to reproduce it** (as minimally and precisely as possible):
You can find my versions in the workflow above and the structure/what I'm providing above as well.
