### ISSUE TITLE
[Bug] Cannot Lint OCI Repo

### ISSUE THREAD

**Issue by aiell0** [helm/chart-testing#707]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: 
Helm v3.16.2
Kubernetes 1.31
ct version 3.12.0

**What happened**:
Attempted to lint a subchart using `ct`.

**What you expected to happen**:
Lint successfully.

**How to reproduce it** (as minimally and precisely as possible):
Have a ct.yaml file with the following:

```
chart-repos:
  - aws-alb-controller=https://aws.github.io/eks-charts
  - crossplane=https://charts.crossplane.io/stable
  - cert-manager=https://charts.jetstack.io
  - datadog-agent=https://helm.datadoghq.com
  - external-secrets=https://charts.external-secrets.io
  - reloader=https://stakater.github.io/stakater-charts
  - alb-controller=oci://mcr.microsoft.com/application-lb/charts
 ```

And run this from the root of the repo:

`ct lint --config=ctconfig.yaml --charts cluster-addons/azure-alb-system --validate-maintainers=false --target-branch main`

In the cluster-addons/azure-alb-system is the chart from [this project](https://artifacthub.io/packages/helm/azure-application-gateway-for-containers/alb-controller). I have the Chart.yaml set as follows:

```
apiVersion: v2
name: azure-alb-system
description: Azure Application Load Balancer Controller
type: application
version: 0.1.0
kubeVersion: ">=1.29.0-0"
appVersion: "1.3.7"
sources:
  - "https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/"
  - "https://artifacthub.io/packages/helm/azure-application-gateway-for-containers/alb-controller"
dependencies:
  - name: alb-controller
    version: 1.3.7
    repository: "oci://mcr.microsoft.com/application-lb/charts"
    alias: azure-alb-system
    condition: azure-alb-system.enabled
```

The above works when I do a `helm dependency build` inside of the directory so I know it is working. My values file is the following:

```
azure-alb-system:
  enabled: false
  albController:
    namespace: "azure-alb-system"
    podIdentity:
      clientID:
```

**Anything else we need to know**: That should be it!
